import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Beta Disclaimer — Prompsy",
  description:
    "Important information about the Prompsy Beta. Understand the limitations, known issues, and expectations when using a pre-release version of the app.",
};

const LAST_UPDATED = "June 6, 2026";

const warnings = [
  {
    icon: "⚠️",
    title: "Beta Software",
    description:
      "Prompsy is currently in Beta. This means the software is still under active development and may contain bugs, incomplete features, or unexpected behaviour.",
  },
  {
    icon: "💾",
    title: "Data Loss Risk",
    description:
      "While we take care to protect your data, beta software can be unstable. We strongly recommend not relying on Prompsy as your sole system for critical work.",
  },
  {
    icon: "🔄",
    title: "Frequent Updates",
    description:
      "The App may be updated frequently during the beta period. Updates can change features, UI, or settings. We will notify you of significant changes.",
  },
  {
    icon: "🤖",
    title: "AI Output Variability",
    description:
      "AI-enhanced prompts are generated by third-party models and may produce variable quality output. Always review before use in critical workflows.",
  },
];

const sections = [
  {
    id: "what-is-beta",
    title: "1. What Is Beta?",
    body: `The Prompsy Beta is a pre-release version of the application made available to a limited group of early-access users. Beta software is not final — it may be incomplete, contain known or unknown bugs, and is subject to significant changes before the official public release. By accepting beta access, you acknowledge that you are using pre-release software with all associated limitations.`,
  },
  {
    id: "no-warranty",
    title: "2. No Warranty During Beta",
    body: `The Prompsy Beta is provided strictly "as is" and "as available." We make no warranties, express or implied, including but not limited to: uninterrupted or error-free operation, fitness for a particular purpose, security against all vulnerabilities, or data integrity. To the fullest extent permitted by applicable law, we disclaim all liability for any damages arising from your use of the Beta software.`,
  },
  {
    id: "service-availability",
    title: "3. Service Availability",
    body: `During the Beta period, we do not guarantee any specific uptime or availability SLA (Service Level Agreement). We may take the service offline for maintenance, updates, or infrastructure changes without prior notice. AI enhancement features depend on third-party API availability (OpenAI, Anthropic). Outages or rate limits from those providers may affect the App's functionality.`,
  },
  {
    id: "data-handling",
    title: "4. Data Handling During Beta",
    body: `We take data privacy seriously, even during Beta. All data handling during the Beta period is governed by our Privacy Policy. However, be aware that: database schema changes during beta may require data migrations; in rare cases, data migrations could result in data loss; we will always attempt to notify you before any such operations. If you are concerned about data continuity, we recommend keeping personal backups of any content you create using Prompsy.`,
  },
  {
    id: "feedback",
    title: "5. Beta Feedback & Bug Reporting",
    body: `By using the Prompsy Beta, you agree to: report bugs, crashes, and unexpected behaviour to our team; provide honest feedback on your experience; and understand that your usage data may be used to improve the product. You can report issues via support@prompsy.app or through the in-app feedback button. We genuinely appreciate your time and feedback — early users like you make Prompsy better for everyone.`,
  },
  {
    id: "feature-changes",
    title: "6. Feature Changes & Deprecation",
    body: `Features available during Beta are not guaranteed to remain in the final product. Features may be changed, renamed, moved, or removed without notice. We will communicate significant feature changes via email to registered beta users. Subscription pricing, feature tiers, and limits are subject to change between Beta and General Availability (GA).`,
  },
  {
    id: "compatibility",
    title: "7. System Compatibility",
    body: `The Prompsy Beta is currently being tested on specific operating system versions. While we aim for broad compatibility, the Beta may not function correctly on all system configurations, OS versions, or hardware setups. Supported platforms during Beta: Windows 10/11 (x64). macOS 12 Monterey and above. Please check our website for the latest compatibility information before installing.`,
  },
  {
    id: "clipboard-beta",
    title: "8. Clipboard Access — Beta Considerations",
    body: `Because Prompsy intercepts clipboard data as a core mechanic, we advise extra caution during Beta: Do not use the App if you regularly copy sensitive information (passwords, private keys, financial data) and are concerned about any potential clipboard capture edge cases. We have engineered the App to only access the clipboard when explicitly triggered, but we recommend reviewing our Privacy Policy for full details. Report any unexpected clipboard behaviour immediately.`,
  },
  {
    id: "termination-of-beta",
    title: "9. End of Beta",
    body: `The Beta period will end when we announce General Availability (GA) of Prompsy. At that time: Free beta users may be transitioned to a free-tier account with usage limits. Paid beta subscribers will be notified of any pricing or plan changes with at least 14 days' notice. We intend to honour all commitments made to early beta supporters.`,
  },
  {
    id: "contact",
    title: "10. Questions & Support",
    body: `For Beta-specific questions, bug reports, or feedback, please contact us at: support@prompsy.app. Subject line: "Beta Feedback" or "Beta Bug Report". We read every email from our beta users and respond as quickly as we can. Thank you for being part of the Prompsy journey from the very beginning.`,
  },
];

export default function BetaDisclaimerPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)] font-sans">
      {/* Header */}
      <header className="sticky top-0 z-50 flex justify-center pt-4 px-4">
        <div className="w-full max-w-4xl bg-[#111111] rounded-full flex items-center px-6 py-3 shadow-lg">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-7 h-7 bg-white rounded-full flex items-center justify-center">
              <img src="/logo.png" alt="Prompsy Logo" className="w-4 h-4 object-contain" />
            </div>
            <span className="text-white font-semibold text-sm tracking-tight">Prompsy</span>
          </Link>
          <Link
            href="/"
            className="ml-auto text-white text-xs font-semibold px-4 py-1.5 rounded-full border border-white/20 hover:bg-white/10 transition-all"
          >
            ← Back to Home
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="flex flex-col items-center text-center pt-16 pb-10 px-6">
        <div className="bg-[#111111] text-white px-4 py-1.5 rounded-full text-[10px] font-bold tracking-widest mb-6 flex items-center gap-2 uppercase shadow-xl">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="12" cy="12" r="10" />
            <path d="m4.93 4.93 4.24 4.24M14.83 9.17l4.24-4.24M14.83 14.83l4.24 4.24M9.17 14.83l-4.24 4.24" />
          </svg>
          Beta Access
        </div>
        <h1 className="text-4xl md:text-5xl font-extrabold text-[#111111] tracking-tight mb-4 leading-tight">
          Beta{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#8b5cf6] to-[#3b82f6]">
            Disclaimer
          </span>
        </h1>
        <p className="text-[#666666] text-base max-w-xl font-medium leading-relaxed">
          You're using an early version of Prompsy. We want to be fully transparent about
          what that means for you.
        </p>
        <p className="text-[#999999] text-sm mt-4">Last updated: {LAST_UPDATED}</p>
      </section>

      {/* Warning Cards */}
      <div className="max-w-3xl mx-auto px-6 mb-10">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {warnings.map((w) => (
            <div key={w.title} className="neu-card p-6 flex gap-4 items-start">
              <span className="text-2xl shrink-0">{w.icon}</span>
              <div>
                <h3 className="text-sm font-bold text-[#111111] mb-1">{w.title}</h3>
                <p className="text-xs text-[#666666] leading-relaxed">{w.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 pb-24">
        {/* Table of Contents */}
        <div className="neu-card p-8 mb-10">
          <h2 className="text-base font-bold text-[#111111] mb-4 tracking-tight">Table of Contents</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-y-2 gap-x-6">
            {sections.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-sm text-[#8b5cf6] hover:text-[#7c3aed] transition-colors font-medium"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </div>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section) => (
            <div
              key={section.id}
              id={section.id}
              className="neu-card p-8 scroll-mt-24"
            >
              <h2 className="text-lg font-bold text-[#111111] mb-4 tracking-tight">
                {section.title}
              </h2>
              <p className="text-[#555555] text-sm leading-relaxed">{section.body}</p>
            </div>
          ))}
        </div>

        {/* Appreciation card */}
        <div className="mt-10 rounded-2xl bg-gradient-to-r from-[#8b5cf6] to-[#3b82f6] p-[1px]">
          <div className="bg-[#f4f5f7] rounded-2xl p-8 text-center">
            <div className="text-3xl mb-3">🚀</div>
            <h3 className="text-base font-bold text-[#111111] mb-2">Thank You for Being Here Early</h3>
            <p className="text-[#666666] text-sm leading-relaxed max-w-md mx-auto">
              You're one of the first people to use Prompsy. Your feedback directly shapes the product.
              We're grateful for your trust and patience as we build something truly great.
            </p>
            <a
              href="mailto:support@prompsy.app?subject=Beta Feedback"
              className="inline-block mt-5 bg-[#111111] hover:bg-black text-white font-semibold text-sm px-8 py-3 rounded-xl transition-all shadow-md"
            >
              Share Feedback
            </a>
          </div>
        </div>

        {/* Footer nav */}
        <div className="mt-12 flex flex-wrap gap-3 justify-center">
          <Link href="/privacy-policy" className="text-xs text-[#8b5cf6] hover:underline font-medium">Privacy Policy</Link>
          <span className="text-[#ccc] text-xs">·</span>
          <Link href="/terms" className="text-xs text-[#8b5cf6] hover:underline font-medium">Terms of Service</Link>
          <span className="text-[#ccc] text-xs">·</span>
          <Link href="/refund-policy" className="text-xs text-[#8b5cf6] hover:underline font-medium">Refund Policy</Link>
        </div>
      </main>

      {/* Footer curve */}
      <div className="w-full relative shrink-0">
        <svg viewBox="0 0 1440 80" className="w-full h-auto block" preserveAspectRatio="none">
          <path d="M0,80 L1440,80 L1440,0 C960,60 480,60 0,0 Z" fill="#111111" />
        </svg>
        <footer className="bg-[#111111] w-full py-6 -mt-1 text-center">
          <p className="text-white/40 text-xs">© {new Date().getFullYear()} Prompsy. All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
}
